import streamlit as st
from streamlit_pandas_profiling import st_profile_report


def display_sidebar():
    """
    Display the sidebar with the app title and navigation options.

    Returns:
    - str: Selected navigation option.
    """
    st.image('https://www.onepointltd.com/wp-content/uploads/2020/03/inno2.png')
    st.title('AutoStreamML App')
    return st.radio('Navigation', ('Upload', 'Profiling', 'Modeling'))


def display_data_upload():
    """
    Display file uploader for data upload.

    Returns:
    - file: File uploaded by the user.
    """
    st.title('Upload Your Data for Modelling')
    return st.file_uploader('Upload Your Dataset', type='csv')


def display_data_frame(df):
    """
    Display DataFrame in the Streamlit app.

    Parameters:
    - df (pd.DataFrame): DataFrame to be displayed.
    """
    st.dataframe(df)


def display_profiling_report(report):
    """
    Display profiling report generated using Streamlit-Pandas-Profiling.

    Parameters:
    - report (ProfileReport): Profiling report generated by ydata_profiling.
    """
    st_profile_report(report)


def display_error(message):
    """
    Display error message.

    Parameters:
    - message (str): Error message to be displayed.
    """
    st.error(message)
